### ISSUE TITLE
增加发布到多个地址的功能

### ISSUE THREAD

**Issue by opoo** [opoo/opoopress#15]
希望增加同一个站点可发布到多个地址（服务器）的功能。

例如将站点发布到国内外不同的服务器节点，然后对域名进行智能 DNS 解析，就可以实现各地快速访问（类似 CDN）。

**Comment by opoo** [comment]
2.0+ 支持。

配置如下：
```yaml
deploy:
- {id: id1, url: 'scp://server1.com/var/www/html'}
- id: "github"
  url: "github://github.com/repositoryOwner/repositoryName/"
  branch: "refs/heads/gh-pages"
```
